/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dalex
 */
public class VisPrincipal extends javax.swing.JFrame {
    int Xmov, Ymov;
     public VisHorario vishorario =new VisHorario();

    /**
     * Creates new form VisPrincipal
     */
    public VisPrincipal() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel3, "src/Imagenes/banner.png");
        ImageIcon iconoa = new ImageIcon(getClass().getResource("/Imagenes/aulas.png"));
        jbtnAulas.setIcon(iconoa);
        jbtnFeriados.setBackground(Color.WHITE);
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/calendar.png"));
        jbtnFeriados.setIcon(icono);
         ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/nuevo.png"));
        jbtnEspacios.setIcon(icon);
        jbtnEspacios.setBackground(Color.WHITE);
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagenes/aguser.png"));
        jbtnGestionPersonas.setIcon(ico);
        jbtnGestionPersonas.setBackground(Color.WHITE);
      //  ImageIcon iconoL = new ImageIcon(getClass().getResource("/Imagenes/lista_reserva.png"));
        //jbtnListado.setIcon(iconoL);
        //jbtnListado.setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        jPanel2.setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnAulas = new javax.swing.JButton();
        jbtnFeriados = new javax.swing.JButton();
        jbtnGestionPersonas = new javax.swing.JButton();
        jbtnEspacios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPnl_salida = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPnl_min = new javax.swing.JPanel();
        jLbl_min = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/fondo_escritorio.png"));
        Image imagen= icon.getImage();
        jdskEscritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(imagen,0,0,getWidth(), getHeight(),this);
            }
        };
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(110, 7, 7));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAulas.setFont(new java.awt.Font("Microsoft Uighur", 1, 30)); // NOI18N
        jbtnAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aulas.png"))); // NOI18N
        jbtnAulas.setText("Espacios");
        jbtnAulas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnAulas.setBackground(Color.WHITE);
        jbtnAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAulasActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 162, 78));

        jbtnFeriados.setFont(new java.awt.Font("Microsoft Uighur", 1, 30)); // NOI18N
        jbtnFeriados.setText("Feriados");
        jbtnFeriados.setActionCommand("");
        jbtnFeriados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnFeriados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFeriadosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnFeriados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 162, 78));

        jbtnGestionPersonas.setFont(new java.awt.Font("Microsoft Uighur", 1, 30)); // NOI18N
        jbtnGestionPersonas.setText("Personas");
        jbtnGestionPersonas.setActionCommand("");
        jbtnGestionPersonas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnGestionPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGestionPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGestionPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 160, 78));

        jbtnEspacios.setFont(new java.awt.Font("Microsoft Uighur", 1, 30)); // NOI18N
        jbtnEspacios.setText("<html><body style='text-align: center'>Nuevo Espacio</body></html>");
        jbtnEspacios.setActionCommand("");
        jbtnEspacios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEspaciosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEspacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 162, 78));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 570));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(530, 420));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnl_salida.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPnl_salidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnl_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPnl_salidaMouseExited(evt);
            }
        });
        jPnl_salida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("   X");
        jPnl_salida.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel3.add(jPnl_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 50, 30));

        jPnl_min.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPnl_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnl_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPnl_minMouseExited(evt);
            }
        });
        jPnl_min.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbl_min.setBackground(new java.awt.Color(0, 0, 0));
        jLbl_min.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLbl_min.setText("   -");
        jPnl_min.add(jLbl_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel3.add(jPnl_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 50, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 30));

        jdskEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jdskEscritorioLayout = new javax.swing.GroupLayout(jdskEscritorio);
        jdskEscritorio.setLayout(jdskEscritorioLayout);
        jdskEscritorioLayout.setHorizontalGroup(
            jdskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jdskEscritorioLayout.setVerticalGroup(
            jdskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jdskEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 1030, 580));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1140, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPnl_salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_salidaMouseClicked
        int mensaje = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "Confirmación de salida", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnl_salidaMouseClicked

    private void jPnl_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_salidaMouseEntered
        jPnl_salida.setBackground(Color.red);
    }//GEN-LAST:event_jPnl_salidaMouseEntered

    private void jPnl_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_salidaMouseExited
        jPnl_salida.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPnl_salidaMouseExited

    private void jPnl_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_minMouseClicked
        setExtendedState(JFrame.ICONIFIED);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPnl_minMouseClicked

    private void jPnl_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_minMouseEntered
        jPnl_min.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jPnl_minMouseEntered

    private void jPnl_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnl_minMouseExited
        jPnl_min.setBackground(Color.white);
    }//GEN-LAST:event_jPnl_minMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - Xmov, y - Ymov);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        Xmov = evt.getX();
        Ymov = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jbtnAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAulasActionPerformed
        this.vishorario.show(true);
        this.vishorario.consumirVistaPrincipal(this);
        if (this.jdskEscritorio.getComponentCount() < 1) {
            this.jdskEscritorio.add(this.vishorario);
            this.jdskEscritorio.updateUI();
        } else {
            JOptionPane.showMessageDialog(this.jdskEscritorio, "No puede generar mas de 1 Ventana");
        }
    }//GEN-LAST:event_jbtnAulasActionPerformed

    private void jbtnFeriadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFeriadosActionPerformed
        VistaNuevoFeriado vf = new VistaNuevoFeriado();
        vf.consumirDatos(this,this.vishorario);
        vf.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFeriadosActionPerformed

    private void jbtnEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEspaciosActionPerformed
        VistNuevosEspacios visE = new VistNuevosEspacios();
        visE.consumirDatos(this);
        visE.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEspaciosActionPerformed

    private void jbtnGestionPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGestionPersonasActionPerformed
        CRUDDocentes cru = new CRUDDocentes();
        cru.consumirVistaReserva(null,this);
        cru.setVisible(true);
        this.dispose();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnGestionPersonasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbl_min;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnl_min;
    public javax.swing.JPanel jPnl_salida;
    public javax.swing.JButton jbtnAulas;
    private javax.swing.JButton jbtnEspacios;
    private javax.swing.JButton jbtnFeriados;
    private javax.swing.JButton jbtnGestionPersonas;
    public javax.swing.JDesktopPane jdskEscritorio;
    // End of variables declaration//GEN-END:variables
}
